# -*- coding: utf-8 -*-
"""censos_ar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pft3jEhDozVpD9r-DTrS64SQ9q22ccoU
"""

import matplotlib.pyplot as plt

import numpy as np

x = [2013,2014,2015,2016,2017,2018,2019] 
y = [415000,670000,1110000,1090000,2075000,2175000,3490000]

plt.figure(figsize=(10,6))
plt.plot(x,y, marker='o',linestyle='--',color='PINK')
plt.xlabel("Años")
plt.ylabel("Ventas")
plt.title("Ranking de ventas")
plt.xticks(x)
plt.show()

plt.figure(figsize=(10,6))
plt.bar (x,y, color='PINK')
plt.xlabel("Años")
plt.ylabel("Ventas")
plt.title("Ranking de ventas")
plt.xticks(x)
plt.show()